name: test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: psf/black@stable

  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: |
        pip install pytest
        pytest tests
